---
- name: Cisco IOS Backup Playbook
  hosts: ciscoen
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Backup running configuration
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: "/var/lib/awx/projects/output/cisco/"
      register: backup_output

    - name: Show backup result
      debug:
        msg: "Backup saved: {{ backup_output.backup_path }}"
