---
- name: Cisco backup via raw SSH (works with restricted AAA)
  hosts: jsc
  gather_facts: no
  connection: ssh
  vars:
    backup_dir: "/var/lib/awx/projects/output/jsc"

  tasks:
    - name: Collect running configuration
      shell: >
        ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }}
        "show running-config"
      register: raw_output

    - name: Save backup locally
      copy:
        content: "{{ raw_output.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}.cfg"
