---
- name: Cisco Backup (Restricted AAA)
  hosts: jsc
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: ""
    backup_dir: "/var/lib/awx/projects/output/jsc"

  tasks:
    - name: Run "show running-config" manually
      ios_command:
        commands:
          - show running-config
      register: show_run_output

    - name: Save running config locally
      copy:
        content: "{{ show_run_output.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}.cfg"
