---
- name: Save Configurations (IOS)
  hosts: cisco
  gather_facts: no
  ignore_errors: yes
  vars:
    creds:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands: show run
      register: show_run_ios

    - copy:
        content: "{{ show_run_ios.stdout[0] }}"
        dest: "/var/lib/awx/projects/output/cisco/{{ inventory_hostname }}.txt"
