- hosts: jsc
  gather_facts: no
  tasks:
    - name: Run Backup (with sshpass + expect)
      block:
        - name: Gather running-config
          community.general.expect:
            command: >
              sshpass -p '{{ ansible_ssh_pass }}'
              ssh -o StrictHostKeyChecking=no -p {{ ansible_ssh_port }}
              {{ ansible_user }}@{{ inventory_hostname }}
            responses:
              'Password:': '{{ ansible_ssh_pass }}'
              '[>#]': 'enable\n'
              'Password:': '{{ ssh_enable_pass }}'
              '[#]': 'terminal length 0\nshow running-config\nexit\n'
          register: export
          delegate_to: localhost

        - name: store export to local file
          ansible.builtin.copy:
            content: "{{ export.stdout }}"
            dest: "/var/lib/awx/projects/output/cisco/{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}.config"
          delegate_to: localhost
