---
- name: Backup Mikrotik and Push to GitHub
  hosts: mikrotik
  gather_facts: false
  vars:
    ansible_ssh_extra_args: '-o HostKeyAlgorithms=ssh-rsa'
    github_token: "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"
    owner: "masoudigram"
    repo: "ansible"
    backup_dir: "/home/msd"
  tasks:
    - name: Export
      ansible.builtin.shell: >-
        sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa  {{ ansible_user }}@{{ inventory_hostname }} /export
      register: export

    - name: Upload Export to GitHub
      uri:
        url: https://api.github.com/repos/{{ owner }}/{{ repo }}/contents/back.txt
        method: PUT
        headers:
          Authorization: "Bearer {{ github_token }}"
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "message": "Adding MikroTik export",
            "content": "{{ export.stdout | b64encode }}"
          }
      register: github_upload

    - debug:
        var: github_upload
