---
- name: Backup Mikrotik
  hosts: mikrotik
  gather_facts: false
  vars:
    ansible_ssh_extra_args: '-o HostKeyAlgorithms=ssh-rsa'
    github_token: "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"
    owner: "masoudigram"
    repo: "ansible"
    backup_dir: "/home/msd"
  tasks:
    - name: Export
      ansible.builtin.shell: >-
        sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa  {{ ansible_user }}@{{ inventory_hostname }} /export
      register: export
      delegate_to: localhost

    - name: Save Export to GitHub
      uri:
        url: "https://api.github.com/repos/masoudigram/ansible/contents/{{ inventory_hostname }}_config/{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
        method: PUT
        headers:
          Authorization: "token {{ github_token }}"
        body_format: json
        body:
          message: "Backup {{ inventory_hostname }} configuration"
          content: "{{ export.stdout | b64encode }}"
        dest: "masoudigram/ansible"  # Update this path to a writable directory
      when: export is defined
      delegate_to: localhost
