---
- name: Backup MikroTik Router Config and Push to GitHub
  hosts: 192.168.10.176  # assuming this is the IP address of your MikroTik router
  gather_facts: no

  tasks:
    - name: Fetch MikroTik Backup
      fetch:
        src: "/flash/{{ ansible_hostname }}-{{ ansible_date_time.date }}.backup"
        dest: "/home/msd/backups"
        flat: yes
        fail_on_missing: no

    - name: Check if Backup Exists
      stat:
        path: "/home/msd/backups/{{ ansible_hostname }}-{{ ansible_date_time.date }}.backup"
      register: backup_file

    - name: Commit Backup to GitHub
      when: backup_file.stat.exists == True
      github_repo:
        user: masoudigram
        token: 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
        repo: ansible  # Replace 'your_repo_name' with the name of your GitHub repository
        dest: "backups/{{ ansible_hostname }}-{{ ansible_date_time.date }}.backup"
        src: "/home/msd/backups/{{ ansible_hostname }}-{{ ansible_date_time.date }}.backup"
