- hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Run BackUp
      block:
        - name: run command
          no_log: false
          ansible.builtin.shell: >-
            sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -p {{ ansible_ssh_port }} {{ ansible_user }}@{{ inventory_hostname }} /ip firewall address-list add 
          register: export
          delegate_to: localhost
