---
- name: Run export command on MikroTik device via telnet
  hosts: mikrotik
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_connection: telnet

  tasks:
    - name: Run export command
      raw: export
      register: output

    - debug:
        var: output.stdout
