---
- name: Run export command on MikroTik device via Telnet
  hosts: mikrotik
  gather_facts: no
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Telnet to MikroTik device and run export command
      expect:
        command: telnet {{ inventory_hostname }}
        responses:
          login: "admin"
          Password: "password"
          "/[>#] $/": "export"
      register: telnet_output

    - debug:
        var: telnet_output.stdout_lines
